// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiS6c52uYMXonohOwIv17T8Lv4yPgJ6Y',
    appId: '1:592025158422:web:22dd42b6f0abed70b00637',
    messagingSenderId: '592025158422',
    projectId: 'moneyminder-c5285',
    authDomain: 'moneyminder-c5285.firebaseapp.com',
    storageBucket: 'moneyminder-c5285.appspot.com',
    measurementId: 'G-8NLNP12BXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkjd-AKGtgz6q8GQXbaiu61AGmYIal22w',
    appId: '1:592025158422:android:2d40643b0d7383f3b00637',
    messagingSenderId: '592025158422',
    projectId: 'moneyminder-c5285',
    storageBucket: 'moneyminder-c5285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ7jzwkDi0_0jUnvqrY9KaWrzY3tNpSqw',
    appId: '1:592025158422:ios:462d612b2092eb43b00637',
    messagingSenderId: '592025158422',
    projectId: 'moneyminder-c5285',
    storageBucket: 'moneyminder-c5285.appspot.com',
    iosBundleId: 'com.example.finkuCloneSlicing',
  );
}
